[package]
name = "scioly-bot"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A Discord bot for Science Olympiad, easily adaptable to other use cases."  
repository = "https://www.github.com/EpicTromboneKid/scioly-bot"
homepage = "https://www.github.com/EpicTromboneKid/scioly-bot"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tokio = {version = "1.42", features = ["full"]}
poise = "0.7"
yaml-rust2 = "0.13"
jwalk = "0.9"
chrono = "0.4.39"
rayon = "1.10.0"
rust_search = "2.1.0"
rustls = "0.23"
serde = "^1.0"
serde_json = "^1.0"
google-drive3 = "7.0.0"
rust-fuzzy-search = "0.1.1"
strum = "0.28"
strum_macros = "0.28"
google-docs1 = "7.0.0"
rand = "0.10"
google-sheets4 = "7.0.0"
fuzzydate = "0.4.1"
yup-oauth2 = { version = "12.1.2", features = ["service_account"] }
anyhow = "*"
# mistralrs = { git = "https://github.com/EricLBuehler/mistral.rs.git" }
# roux = "2.2.13"
